services:
  server:
    build:
      context: ./server
      target: production
    network_mode: "host"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3021
      - DATABASE_URL=${DATABASE_URL:-mysql://root:root@127.0.0.1:3306/undercover}
      - JWT_SECRET=${JWT_SECRET:-supersecretundercover}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  client:
    build:
      context: ./client
      target: production
      args:
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-https://undercover-server.coreapps.web.id}
    ports:
      - "3020:3020"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3020
      # Update these values during deployment
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-https://undercover-server.coreapps.web.id}
    depends_on:
      - server
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
